Fix release workflow due to missing Git tag
We should have created a Git tag before calling `changelog-to-github-release-action`
because this action does not support tag auto-creation.

That's why this change resolves the following error:

```
Error: Not found version: 0.4.0
```

https://github.com/stylelint/changelog-to-github-release-action/actions/runs/17796946474/job/50586734189